# ============================================================================
# YAZI — Redtail theme
# ============================================================================

[manager]
cwd = { fg = "#cb5e3d", bold = true }

# Hovered
hovered         = { bg = "#3f1f13" }
preview_hovered = { bg = "#3f1f13" }

# Find
find_keyword  = { fg = "#d6a241", bold = true }
find_position = { fg = "#b6a285" }

# Marker
marker_selected = { fg = "#d6a241", bg = "#0e0907" }
marker_copied   = { fg = "#79ba58", bg = "#0e0907" }
marker_cut      = { fg = "#ca4949", bg = "#0e0907" }

# Tab
tab_active   = { fg = "#0e0907", bg = "#d6a241" }
tab_inactive = { fg = "#b6a285", bg = "#3f1f13" }
tab_width    = 1

# Count
count_copied   = { fg = "#0e0907", bg = "#79ba58" }
count_cut      = { fg = "#0e0907", bg = "#ca4949" }
count_selected = { fg = "#0e0907", bg = "#d6a241" }

# Border
border_symbol = "│"
border_style  = { fg = "#745234" }

[status]
overall   = { fg = "#b6a285" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Mode
mode_normal = { fg = "#0e0907", bg = "#d6a241", bold = true }
mode_select = { fg = "#0e0907", bg = "#79ba58", bold = true }
mode_unset  = { fg = "#0e0907", bg = "#ca4949", bold = true }

# Progress
progress_label  = { fg = "#e4d7c2" }
progress_normal = { fg = "#745234" }
progress_error  = { fg = "#ca4949" }

# Permissions
perm_type = { fg = "#d6a241" }
perm_read = { fg = "#79ba58" }
perm_write = { fg = "#ca4949" }
perm_exec = { fg = "#cb5e3d" }
perm_sep = { fg = "#745234" }

[input]
border   = { fg = "#d6a241" }
title    = { fg = "#d6a241" }
value    = { fg = "#e4d7c2" }
selected = { bg = "#3f1f13" }

[select]
border   = { fg = "#d6a241" }
active   = { fg = "#d6a241", bold = true }
inactive = { fg = "#b6a285" }

[tasks]
border  = { fg = "#d6a241" }
title   = { fg = "#d6a241" }
hovered = { fg = "#d6a241" }

[which]
mask            = { bg = "#0e0907" }
cand            = { fg = "#4fafac" }
rest            = { fg = "#745234" }
desc            = { fg = "#b6a285" }
separator       = "  "
separator_style = { fg = "#745234" }

[help]
on      = { fg = "#d6a241" }
run     = { fg = "#b6a285" }
desc    = { fg = "#e4d7c2" }
hovered = { bg = "#3f1f13" }
footer  = { fg = "#b6a285" }

[filetype]

rules = [
    # Media
    { mime = "image/*", fg = "#b166c0" },
    { mime = "video/*", fg = "#cb5e3d" },
    { mime = "audio/*", fg = "#e1b65a" },

    # Archives
    { mime = "application/zip",  fg = "#ca4949" },
    { mime = "application/gzip", fg = "#ca4949" },
    { mime = "application/x-tar", fg = "#ca4949" },
    { mime = "application/x-7z-compressed", fg = "#ca4949" },

    # Documents
    { mime = "application/pdf",  fg = "#639cce" },
    { mime = "application/json", fg = "#d6a241" },

    # Directories
    { url = "*/", fg = "#e1b65a", bold = true },

    # Fallback
    { name = "*",  fg = "#e4d7c2" },
]
